collection_name: agent # 向量数据库表名
persist_directory: chroma_db #向量数据库文件名
k: 3
data_path: ../data # 数据文件夹
md5_hex_store: md5.text # 去重记录
allow_knowledge_file_type: [ "txt", "pdf" ]

chunk_size: 200
chunk_overlap: 20
separators: [ "\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", "" ]
